"""Machine-readable log of evidence-driven modelling decisions.

Every time the EDA discovers something that could influence retrieval,
prompting, reranking, fine-tuning, evaluation or post-processing, we append a
structured entry here. The result is `MODELLING_DECISIONS.md`, which becomes the
blueprint for the implementation phase.

Entries are also cached as JSON so re-running the notebook rebuilds a clean,
de-duplicated document rather than appending forever.
"""
from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field

from . import config as C

_JSON = C.ART_DIR / "modelling_decisions.json"

_PRIORITY_ORDER = {"High": 0, "Medium": 1, "Low": 2}


@dataclass
class Decision:
    id: str                    # short stable slug, e.g. "lang-imbalance"
    section: str               # EDA section that produced it
    observation: str
    evidence: str
    impact: str
    recommendation: str
    priority: str              # High | Medium | Low
    tags: list[str] = field(default_factory=list)  # retrieval, prompting, ...


def _load() -> dict[str, dict]:
    if _JSON.exists():
        return json.loads(_JSON.read_text())
    return {}


def record(dec: Decision) -> None:
    """Add/replace a decision (keyed by id) and rewrite the JSON + Markdown."""
    if dec.priority not in _PRIORITY_ORDER:
        raise ValueError(f"priority must be High/Medium/Low, got {dec.priority!r}")
    store = _load()
    store[dec.id] = asdict(dec)
    _JSON.write_text(json.dumps(store, indent=2, ensure_ascii=False))
    _render(store)


def _render(store: dict[str, dict]) -> None:
    items = sorted(
        store.values(),
        key=lambda d: (_PRIORITY_ORDER.get(d["priority"], 9), d["section"]),
    )
    lines = [
        "# Modelling Decisions",
        "",
        "> Auto-generated by the EDA. Each entry is an **evidence-driven** finding "
        "that should shape the retrieval + multilingual LLM system. "
        "Sorted by priority.",
        "",
        f"**Total findings:** {len(items)} "
        f"(High: {sum(d['priority']=='High' for d in items)}, "
        f"Medium: {sum(d['priority']=='Medium' for d in items)}, "
        f"Low: {sum(d['priority']=='Low' for d in items)})",
        "",
    ]
    for d in items:
        lines += [
            f"## [{d['priority']}] {d['id']} — {d['section']}",
            "",
            f"- **Observation:** {d['observation']}",
            f"- **Evidence:** {d['evidence']}",
            f"- **Likely impact:** {d['impact']}",
            f"- **Recommended action:** {d['recommendation']}",
            f"- **Tags:** {', '.join(d['tags']) if d['tags'] else '—'}",
            "",
        ]
    C.DECISIONS_MD.write_text("\n".join(lines))


def reset() -> None:
    """Wipe the store so a fresh notebook run starts from an empty document."""
    if _JSON.exists():
        _JSON.unlink()
    _render({})
