"""Section 17 — Assemble DATASET_ANALYSIS_REPORT.md from saved artefacts.

The report is generated from the CSVs in outputs/tables and the decisions JSON
so it always reflects the latest run (reproducible, no hand-copied numbers).
Narrative text references values read back from those tables.
"""
from __future__ import annotations

import json

import pandas as pd

from . import config as C


def _t(name: str) -> pd.DataFrame:
    """Load a saved table CSV by name (index in first column where applicable)."""
    return pd.read_csv(C.TAB_DIR / f"{name}.csv")


def _md(name: str) -> str:
    p = C.TAB_DIR / f"{name}.md"
    return p.read_text() if p.exists() else "_(table missing)_"


def _decisions_by_priority() -> dict:
    j = json.loads((C.ART_DIR / "modelling_decisions.json").read_text())
    out = {"High": [], "Medium": [], "Low": []}
    for d in j.values():
        out.get(d["priority"], out["Low"]).append(d)
    return out


def build_report() -> str:
    split = _t("01_split_summary")
    dup = _t("01_train_duplicates")
    subset = _t("02_subset_summary_train")
    reuse = _t("04_answer_exact_reuse").set_index("Unnamed: 0")["value"]
    headline = _t("10_retrieval_headline").rename(columns={"Unnamed: 0": "method"})
    per_sub = _t("10_retrieval_hybrid_summary").rename(columns={"Unnamed: 0": "subset"})
    align = _t("06_embedding_alignment")
    val_sim = _t("14_val_nearest_train_sim")
    test_sim = _t("15_test_nearest_train_sim")
    topics = _t("08_topic_distribution")
    decs = _decisions_by_priority()

    # scalars for the narrative
    n_train = int(split.loc[split["split"] == "train", "rows"].iloc[0])
    dup_ans_pct = float(dup.loc[dup["kind"] == "duplicated_answers", "pct_of_rows"].iloc[0])
    uniq_ans = int(float(reuse["n_unique_answers"]))
    dense = headline.set_index("method").loc["dense_e5"]
    n_topics = int((topics["topic_id"] != -1).sum())

    L = []
    A = L.append

    A("# Multilingual Health QA — Dataset Analysis Report\n")
    A("_Internal ML documentation. Auto-generated by the EDA notebook "
      "(`notebooks/health_qa_eda.ipynb`). Figures in `outputs/figures/`, tables in "
      "`outputs/tables/`, machine-readable findings in `MODELLING_DECISIONS.md`._\n")

    # ---- Executive Summary -------------------------------------------- #
    A("## 1. Executive Summary\n")
    A(f"- **Task.** Answer sexual-&-reproductive-health questions across **8 "
      f"language-country subsets** (English + Akan, Amharic, Luganda, Swahili) from "
      f"Ghana, Uganda, Kenya, Ethiopia. Train has **{n_train:,}** Q/A rows; the "
      f"submission is scored on **three** targets — ROUGE-L F1, ROUGE-1 F1 and an "
      f"**LLM judge** (`TargetRLF1`, `TargetR1F1`, `TargetLLM`).")
    A(f"- **Answers are largely canonical, not individually written.** "
      f"**{dup_ans_pct:.0f}%** of answers are exact duplicates and only "
      f"{uniq_ans:,} answers are unique; ~29% are near-duplicates. Many distinct "
      f"questions map to one answer.")
    A(f"- **Retrieval works — and dense beats hybrid.** With *zero training*, "
      f"copying the nearest Train answer via **dense e5** scores ROUGE-L "
      f"**{dense['rougeL_f1']:.3f}**, ROUGE-1 **{dense['rouge1_f1']:.3f}**, "
      f"exact **{dense['exact']:.3f}**, topic-match **{dense['topic_match']:.3f}** on "
      f"Val — beating BM25 and a naive RRF hybrid.")
    A("- **But quality is wildly uneven by subset.** English-Kenya/Uganda and "
      "Swahili/Luganda are nearly solved by copy (ROUGE-L 0.47–0.66); Amharic, Akan "
      "and English-Ghana are not (0.17–0.21).")
    A("- **The gap is partly a metric artifact.** For Amharic/Akan the retriever finds "
      "the right, on-topic answer (topic-match 0.97–0.99) yet word-ROUGE stays low "
      "because these languages are morphologically rich — word overlap under-scores "
      "correct answers. The LLM judge will be fairer there.")
    A("- **No distribution shift and no cross-lingual parallelism.** Val and Test are "
      "≈identical to Train (nearest-Train cosine ~0.96); the language subsets are "
      "**not** translations of each other (0% shared IDs).")
    A(f"- **Recommendation (headline).** Ship a **dense-retrieval-first, "
      f"confidence-routed hybrid**: copy/rerank when retrieval is confident; generate "
      f"with a multilingual LLM (retrieved answer as context) when it is not — "
      f"especially for Amharic/Akan/Eng_Ghana. Evaluate and tune **per subset**.\n")

    # ---- Key Statistics ----------------------------------------------- #
    A("## 2. Key Statistics\n")
    A("### 2.1 Splits\n"); A(_md("01_split_summary") + "\n")
    A("### 2.2 Per-subset summary (Train)\n"); A(_md("02_subset_summary_train") + "\n")
    A("### 2.3 Duplication (Train)\n"); A(_md("01_train_duplicates") + "\n")
    A("### 2.4 Retrieval feasibility — headline (Val, retrieve-and-copy)\n")
    A(_md("10_retrieval_headline") + "\n")
    A("### 2.5 Retrieval by subset (dense/hybrid)\n")
    A(_md("10_retrieval_hybrid_summary") + "\n")

    # ---- Major Insights ----------------------------------------------- #
    A("## 3. Major Insights\n")
    insights = [
        ("Canonical answer bank",
         f"{dup_ans_pct:.0f}% exact-duplicate answers, {uniq_ans:,} unique; one answer "
         f"reused up to 68×. Answers are assembled from reusable per-topic blocks "
         f"(e.g. the STI trivia and closings in `04_answer_repeated_sentences`)."),
        ("Eng_Eth topic-tag prefix",
         "2,215 Eng_Eth answers (only) begin 'This is a question about, <TOPIC>.' — "
         "an exploitable style rule AND near-free gold topic labels."),
        ("Dense > hybrid > BM25",
         "Dense e5 retrieval is the strongest zero-training signal; naive RRF hybrid "
         "and BM25 are weaker (`10_retrieval_headline`)."),
        ("Per-subset retrieval variance",
         "ROUGE-L: Eng_Ken 0.66 / Swa_Ken 0.62 / Eng_Uga 0.61 / Lug_Uga 0.47 (strong) "
         "vs Eng_Gha 0.21 / Akan 0.20 / Amharic 0.17 (weak)."),
        ("ROUGE vs morphology",
         "Amharic/Akan: high topic-match (0.97–0.99) but low ROUGE — word-overlap "
         "metrics under-score morphologically rich correct answers "
         "(`13_complexity_answers`, `07_oov_train_val_questions`: Amharic 16% token-OOV)."),
        ("Automatic topics",
         f"BERTopic discovered {n_topics} data-driven health topics (HIV/AIDS, HPV, "
         f"PrEP/PEP, mother-child/breastfeeding, puberty, peer-pressure, digital "
         f"literacy…); mean cluster purity vs Eng_Eth gold ≈0.59 (`08_topic_*`)."),
        ("No translation / parallelism",
         "0% of IDs shared across subsets; non-English↔English cosine 0.85–0.87 vs "
         "0.94–0.98 English–English (`06_*`). Independently authored per language."),
        ("No distribution shift",
         "Val & Test ≈ Train (nearest-Train cosine ~0.96, p10 0.93); language mix "
         "matches within ±5pp (`14_*`, `15_*`). Val is a trustworthy proxy for Test."),
        ("Style: minimal disclaimers",
         "Safety disclaimers appear <1% of the time; bullets <2%. A generator must "
         "NOT add boilerplate or it loses ROUGE (`12_*`)."),
    ]
    for i, (h, body) in enumerate(insights, 1):
        A(f"**{i}. {h}.** {body}\n")

    # ---- Risks -------------------------------------------------------- #
    A("## 4. Risks\n")
    risks = [
        ("Language imbalance", "Eng_Uga 25.6% vs Amh_Eth 6.2% (4.1× ratio). Pooled "
         "training over-serves English; per-subset metrics count equally."),
        ("Low-resource quality", "Amharic/Akan/Eng_Ghana retrieval is weak; these "
         "drag the mean and are hardest to generate for."),
        ("Metric mismatch", "Word-ROUGE penalises correct morphologically-rich "
         "answers; optimising ROUGE alone can hurt the LLM-judge score and vice-versa."),
        ("Ge'ez script", "Amharic uses a different script; tokenizer/embedding "
         "coverage must be verified or retrieval & generation silently degrade."),
        ("Answer ambiguity ceiling", "~4% of questions have >1 valid gold answer — a "
         "hard cap on exact/ROUGE for any system."),
        ("Retrieval failure tail", "A minority of low-similarity questions (e.g. "
         "Eng_Gha, novel Test items) cannot be answered by copy and need generation."),
        ("Long answers", "Akan/Eng_Uga answers reach ~450+ words; truncation or "
         "length mismatch costs ROUGE and coherence."),
        ("Over-cleaning", "Stripping the Eng_Eth prefix or adding disclaimers would "
         "diverge from gold; post-processing must be subset-aware."),
    ]
    for i, (h, body) in enumerate(risks, 1):
        A(f"{i}. **{h}.** {body}")
    A("")

    # ---- Recommended Architecture ------------------------------------- #
    A("## 5. Recommended Architecture (evidence-based)\n")
    A("A **confidence-routed hybrid of dense retrieval + multilingual generation**:\n")
    A("1. **Index** the Train corpus (unique answers + their questions) with "
      "`multilingual-e5-base` question embeddings. *Evidence:* dense retrieval is the "
      "strongest zero-training baseline (§2.4) and the answer bank is canonical (§3.1).")
    A("2. **Retrieve** top-k Train questions per query (dense; BM25 only as a tuned "
      "add-on / rare-term fallback — naive RRF hurt, §3.3).")
    A("3. **Rerank** top-k with a cross-encoder or answer-side similarity; the Q→A "
      "coupling gap (0.87 vs 0.77 shuffled) confirms question-based retrieval is "
      "meaningful (`11_qa_coupling`).")
    A("4. **Route by confidence** (nearest-Train cosine, tuned on Val since Val≈Test, "
      "§3.8): **high** → return/lightly-edit the retrieved canonical answer "
      "(cheap, high ROUGE for Ken/Uga/Swa/Lug); **low** → **generate** with a "
      "multilingual instruction-tuned LLM using the retrieved answer(s) as context "
      "(RAG), for Amharic/Akan/Eng_Ghana and novel questions.")
    A("5. **Post-process per subset**: match target length/style, prepend the Eng_Eth "
      "topic prefix, and do NOT add unsolicited disclaimers (§3.9, `12_*`).")
    A("6. **Evaluate per subset** on both ROUGE and a semantic/LLM-judge proxy; do not "
      "optimise a single global ROUGE (§3.5).\n")
    A("**Model-choice guidance:**\n")
    A("- *Retrieval-only:* strong, cheap baseline; near-solves Kenya/Uganda subsets but "
      "leaves Amharic/Akan/Eng_Ghana far behind → **insufficient alone**.")
    A("- *Retrieval + generation (RAG):* recommended — grounds the LLM in canonical "
      "answers, closes the low-resource gap, and controls style.")
    A("- *Fine-tuning / LoRA:* likely helps for style-matching and low-resource "
      "languages; LoRA is a cost-effective way to adapt a multilingual decoder without "
      "full fine-tuning. Use subset-balanced sampling (§4.1).")
    A("- *Multilingual seq2seq (e.g. mT5/NLLB-style):* reasonable for short-answer "
      "subsets (Amharic/Eng_Eth) but weaker for long free-form answers; **decoder-only "
      "instruction-tuned multilingual LLMs** are the more flexible default.")
    A("- *Hybrid > pure generator:* yes — retrieval provides the canonical content the "
      "metric rewards; generation provides coverage and fluency where copy fails.\n")

    # ---- Modelling decisions digest ----------------------------------- #
    A("## 6. Modelling Decisions (digest — full list in `MODELLING_DECISIONS.md`)\n")
    for pri in ("High", "Medium", "Low"):
        if not decs[pri]:
            continue
        A(f"### {pri} priority\n")
        for d in decs[pri]:
            A(f"- **{d['id']}** — {d['recommendation']}")
        A("")

    # ---- Future Work -------------------------------------------------- #
    A("## 7. Future Work (after first modelling experiments)\n")
    fw = [
        "Measure ORACLE retrieval (best-of-top-k, and copy of the correct canonical "
        "answer) to bound achievable ROUGE per subset.",
        "Add a cross-encoder reranker and quantify its lift over top-1 dense.",
        "Evaluate a stronger/answer-native embedder (BGE-M3, LaBSE) for Amharic/Akan "
        "and cross-lingual retrieval.",
        "Build a proper LLM-judge harness to align local evaluation with `TargetLLM`.",
        "Try char-level / stemmed ROUGE and morphological analysers for Amharic, "
        "Luganda, Akan diagnostics.",
        "Calibrate the retrieval-confidence routing threshold and measure generation "
        "vs copy per subset.",
        "Cluster the retrieval failure cases to characterise what generation must "
        "handle.",
        "Deduplicate/normalise the canonical answer bank and pick a representative "
        "answer per cluster.",
    ]
    for i, f in enumerate(fw, 1):
        A(f"{i}. {f}")
    A("")

    text = "\n".join(L)
    C.REPORT_MD.write_text(text)
    return text
